services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    expose:
      - "8000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - ORIGIN=http://localhost:3000
      - BACKEND_HOST=http://backend:8000
