services:
  backend:
    build:
      context: ./backend
    ports:
      - "127.0.0.1:8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        - PUBLIC_BACKEND_HOST=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - ORIGIN=${ORIGIN}
