services:
  backend:
    # image: sjerzykiewicz/noname-surveys-backend:dev
    build:
      context: ./backend
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - ./backend/.env

  frontend:
    # image: sjerzykiewicz/noname-surveys-frontend:dev
    build:
      context: ./frontend
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
