name: dockerize-dev

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    

jobs:
  dockerize-front:
    if: ${{ github.files_changed.contains('frontend/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build ./frontend/. --file ./frontend/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/noname-surveys-frontend:dev
        
      - name: Docker push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/noname-surveys-frontend:dev

  dockerize-back:
    if: ${{ github.files_changed.contains('backend/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build ./backend/. --file ./backend/Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/noname-surveys-backend:dev
        
      - name: Docker push
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/noname-surveys-backend:dev